### ISSUE TITLE
Coding Guidelines: Add SciPy/NumPy section

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/greps#6]
@jdemel commented this would be useful.

**Comment by jdemel** [comment]
I'll write something on it.  You can assign me to this. 

Here are the thoughts from the PR.
- There's a Boost specific section and we want to have a NumPy/SciPy specific section.
- Important section because problems pops up regularly on the bugtracker.
- Try to avoid SciPy and make use of NumPy constructs.
- SciPy is optional, thus code should have a non-SciPy fallback. Such guidelines would've helped me back in the day.

**Comment by bhilburn** [comment]
A wild @jdemel appears!

And I think this is a great idea. Thanks, @jdemel  `=)`

**Comment by mbr0wn** [comment]
@jdemel I've invited you to gr-devs; once you accept, I can assign you. Thanks a lot!

**Comment by mbr0wn** [comment]
...Your thoughts are all good though, you can start writing PRs without being assigned.

**Comment by jdemel** [comment]
@mbr0wn I got your invite and accepted. I'll start writing as soon as there's time available.

**Comment by mbr0wn** [comment]
PR was merged.
